# ToDo: Edge cases and exception handling
"""
    SQL-like Query in Python:
    -------------------------
    You are given a list of dictionaries representing orders in a simplified format:
    orders = [ {"order_id": 1, "customer": "Alice", "total": 50, "status": "completed"}, {"order_id": 2, "customer": "Bob", "total": 100, "status": "pending"}, {"order_id": 3, "customer": "Alice", "total": 75, "status": "completed"}, ... ] Filter Orders by Status Write a function that takes the orders list and a status string (e.g., "completed") and returns a list of orders that match the given status.
    Calculate Total Revenue by Customer Write a function that calculates and returns the total revenue generated by each
    customer. The output should be a dictionary with customer names as keys and their total revenue as values.
"""

if __name__ == '__main__':
    pass
